##集群名称
cluster.name: hgihdsa-log-cluster

##集群中的这个节点的名称
node.name: highdsa-node-master

##是否是master节点
node.master: true

##是否是数据节点
node.data: true

##日志文件路径
path.logs: /home/hms/elk/elasticsearch

##当JVM开始写入交换空间时（swapping）ElasticSearch性能会低下
##你应该保证它不会写入交换空间设置这个属性为true来锁定内存
##同时也要允许elasticsearch的进程可以锁住内存
##linux下可以通过 ulimit -l unlimited 命令 
bootstrap.memory_lock: true

##集群中 Elasticsearch 节点之间的通信的端口 默认9300
transport.tcp.port: 9300

##绑定的ip地址,允许外网访问
network.host: 0.0.0.0

##Elasticsearch 服务使用的端口
http.port: 9200 

## 一个集群中的N个节点启动后,才允许进行恢复处理
gateway.recover_after_nodes: 1

##当节点(主节点或者数据节点)启动时使用这个列表进行探测其他节点
#discovery.zen.ping.unicast.hosts: ["10.45.32.58", "10.45.32.90", "10.45.32.30", "10.45.32.46"]

##指示某个集群启动所需要的最少的master数量
##官方建议计算方式：=(所有节点数量 / 2)+ 1
##比如一共有5个节点，那么建议设置(5/2)+1=3 个master
discovery.zen.minimum_master_nodes: 1

##探查的超时时间,默认3秒,提高一点以应对网络不好的时候,防止脑裂
discovery.zen.fd.ping_timeout: 10s

##指示是否为Elasticsearch服务启用HTTP
http.enabled: true

###########以下配置避免跨域出现问题################

##是否允许跨源 REST 请求
http.cors.enabled: true
##如果http.cors.enabled 的值为true，那么该属性会指定允许REST请求来自何处
## *代表所有都可以
http.cors.allow-origin: "*"